#!/bin/bash
#  /etc/rc.d/init.d/prometheus
#
# chkconfig: 2345 80 80  // THIS LINE IS READ To enable this service to run on instance reboot
#
# config: /etc/sysconfig/node_exporter.conf	//COMMENT path of arguments file
# pidfile: /var/run/node_exporter.pid  //COMMENT pid file path

# Source function library.

. /etc/init.d/functions


RETVAL=0
PROG="prometheus"
DAEMON_SYSCONFIG=/etc/sysconfig/${PROG}
DAEMON=/usr/local/bin/${PROG}
PID_FILE=/var/run/${PROG}.pid
LOCK_FILE=/var/lock/subsys/${PROG}
LOG_FILE=/var/log/logs/${PROG}.log
DAEMON_USER="prometheus"
GOMAXPROCS=$(grep -c ^processor /proc/cpuinfo)

. ${DAEMON_SYSCONFIG}

start() {
  if check_status > /dev/null; then
    echo "prometheus is already running"
    exit 0
  fi

  echo -n $"Starting prometheus: "
  daemonize -u ${DAEMON_USER} -p ${PID_FILE} -l ${LOCK_FILE} -a -e ${LOG_FILE} -o ${LOG_FILE} ${DAEMON} ${ARGS}
  RETVAL=$?
  echo ""
  return $RETVAL
}

stop() {
    echo -n $"Stopping prometheus: "
    killproc -p ${PID_FILE} -d 10 ${DAEMON}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${LOCK_FILE} ${PID_FILE}
    return $RETVAL
}

check_status() {
    status -p ${PID_FILE} ${DAEMON}
    RETVAL=$?
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        check_status
        ;;
    reload|force-reload)
        reload
        ;;
    restart)
        stop
        start
        ;;
    *)
        N=/etc/init.d/${NAME}
        echo "Usage: $N {start|stop|status|restart|force-reload}" >&2
        RETVAL=2
        ;;
esac

